<?php
/**
 * Implements hook_menu_block_blocks().
 */
function fb_menu_block_header_menu_mobile_menu_block_blocks() {
  return array(
    // The array key is the block id used by menu block.
    'fb_header_menu_mobile' => array(
      // Use the array keys/values described in menu_tree_build().
      'menu_name' => 'menu-header-menu',
      'parent_mlid' => 0,
      'title_link' => FALSE,
      'admin_title' => 'Menu Block - Header Menu Mobile',
      'level' => 1,
      'follow' => 0,
      'depth' => 1,
      'expanded' => 0,
      'sort' => 0,
    ),
  );
}
function fb_menu_block_header_menu_mobile_block_info_alter(&$blocks, $theme, $code_blocks) {
  $blocks['menu_block']['fb_header_menu_mobile']['title'] = "<none>";
}
